---
title: "Statistics common notation"
author: "David Hodge"
date: '2021-05-18'
slug: statistics-common-notation
categories: R
tags: []
---

Statistics notation is very easy in Rmarkdown. 

Below a list of common components of statistics notation for reference.

Greek parameters

$\mu$ 
```{r, eval=F}
$\mu$ 
```

$\alpha$ 
```{r, eval=F}
$\alpha$ 
```

$\beta$ 
```{r, eval=F}
$\beta$ 
```

$\gamma$ 
```{r, eval=F}
$\gamma$ 
```

$\tau$ 
```{r, eval=F}
$\tau$ 
```

$\sigma$ 
```{r, eval=F}
$\sigma$ 
```

Subscript

$H_0$ 
```{r, eval=F}
$H_0$ 
```

$Y_{ij}$ 
```{r, eval=F}
$Y_{ij}$ 
```

Superscript

$\sigma^2$ 
```{r, eval=F}
$\sigma^2$ 
```

Hats and bars

$\hat{Y}$ 
```{r, eval=F}
$\hat{Y}$ 
```

$\bar{Y}$ 
```{r, eval=F}
$\bar{Y}$ 
```

$\hat{f}_i$ 
```{r, eval=F}
$\hat{f}_i$ 
```

Operators

$\ge$ 
```{r, eval=F}
$\ge$ 
```

$\le$ 
```{r, eval=F}
$\le$ 
```

$\neq$ 
```{r, eval=F}
$\neq$ 
```

$\sum{}$ 
```{r, eval=F}
$\sum{}$ 
```

$\triangle{}$
```{r, eval=F}
$\triangle{}$
```

$\sqrt{9}$
```{r, eval=F}
$\sqrt{9}$
```

Fractions

$\frac{3}{4}$
```{r, eval=F}
$\frac{3}{4}$
```

